#!/usr/bin/perl

# Compute the circumference of a circle

print "This program computes the circumference of a circle.\nEnter the radius of the circle:\n";
$radius = <STDIN>;

if ($radius < 0) {
    $circum = 0;
} else {
    $circum = $radius * 2 * 3.141592654;
}

print "The circumference of a circle with a radius of " . chomp($radius) . " is $circum\n";
