#!/bin/bash


# Desktop
printf "\n\nrsync-ing ~/Desktop\n"
/usr/bin/rsync -avzh -e "ssh -p443" /home/cory/Desktop/ cory@$LANSRV:/home/cory/thinkpad/Desktop || { echo "Script error while syncing ~/Desktop" >&2;exit 1; }

# Documents
printf "\n\nrsync-ing ~/Documents\n"
/usr/bin/rsync -avzh -e "ssh -p443" --exclude=**/*LinuxISOs*/ --exclude=**/*WindowsISOs*/ --exclude=**/*CEH_prep*/ /home/cory/Documents/ cory@$LANSRV:/home/cory/thinkpad/Documents || { echo "Script error while syncing ~/Documents" >&2;exit 1; }

# Pictures
printf "\n\nrsync-ing ~/Pictures"
/usr/bin/rsync -avzh -e "ssh -p443" /home/cory/Pictures/ cory@$LANSRV:/home/cory/thinkpad/Pictures || { echo "Script error while syncing ~/Pictures" >&2;exit 1; }

# Scripts
printf "\n\nrsync-ing ~/bin\n"
/usr/bin/rsync -avzh -e "ssh -p443" /home/cory/bin/ cory@$LANSRV:/home/cory/thinkpad/bin || { echo "Script error while syncing ~/bin" >&2;exit 1; }

# Home log files
printf "\n\nrsync-ing ~/logs\n"
/usr/bin/rsync -avzh -e "ssh -p443" /home/cory/logs/ cory@$LANSRV:/home/cory/thinkpad/logs || { echo "Script error while syncing ~/logs" >&2;exit 1; }

printf "\nSuccess\n" && exit 0