#!/usr/bin/perl

# Read a list of numbers and output the corresponding name.

@names = qw( fred betty barney dino wilma pebbles bamm-bamm );

print "Enter numbers:\n";

chomp(@nums = <STDIN>);

foreach (@nums) {
    print "$names[$_ - 1]\n";
}
